Repository MyEtherWallet/mew-components, pull requests merged in 2022-08, with the labels that each got.

#282 fix: persistent hint
  package-lock.json
  package.json
  src/components/MewAddressSelect/MewAddressSelect.vue
  src/components/MewSelect/MewSelect.vue
  src/components/MewTable/MewTable.vue
  src/components/MewTokenContainer/MewTokenContainer.vue
  stories/MewSelect/MewSelect.stories.js
  stories/MewTokenContainer/MewTokenContainer.mdx
  stories/MewTokenContainer/MewTokenContainer.stories.js
Labels: ready

#279 devop: add borderSize prop to mew-token-container
  src/components/MewTokenContainer/MewTokenContainer.vue
  stories/MewTokenContainer/MewTokenContainer.mdx
  stories/MewTokenContainer/MewTokenContainer.stories.js
Labels: ready

#283 devop: Put exact match on top of list of search
  src/components/MewSelect/MewSelect.vue
Labels: enhancement, ready

#284 fix: fix unwanted capitalize style from mew select
  src/components/MewSelect/MewSelect.vue
  stories/MewSelect/MewSelect.stories.js
Labels: bug, ready

#286 fix: mew-select icon width resizing issue
  src/components/MewSelect/MewSelect.vue
Labels: ready

#288 fix: mew-table token icon resizing issue
  src/components/MewTable/MewTable.vue
Labels: ready

#287 fix: mew-tooltip word wrap issue
  src/components/MewTooltip/MewTooltip.vue
Labels: ready

#290 fix: add top arrow and rotating open/close indicator arrow
  package-lock.json
  package.json
  src/components/MewMenu/MewMenu.vue
  src/components/MewTable/MewTable.vue
  src/components/MewTokenContainer/MewTokenContainer.vue
  src/components/MewTooltip/MewTooltip.vue
  yarn.lock
Labels: ready

#275 devop: mew-table fix errors
  src/components/MewTable/MewTable.vue
  yarn.lock
Labels: bug, ready

#292 fix: fix issue with displaying long text inside if the mew-transform-…
  src/components/MewTooltip/MewTooltip.vue
Labels: bug, ready
